[package]
name = "gradle-report-parser"
version = "0.1.0"
authors = ["tkots"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
